### PR TITLE
Set default phone prefix when country is selcted.

### PR DESCRIPTION
**Pull request by phuocngdev**
Also allow controller to pickup selected country from directive

### CODE REVIEW

**Comment by Sjors** [comment]
Thanks! Can you remove the release from the pull request? I'll make a release myself after the merge.

**Comment by phuocngdev** [comment]
Hi, I removed the release

**Comment by jtormey** [comment]
Looks good to me, thanks!

**Comment by Sjors** [comment]
https://github.com/blockchain/bc-phone-number/releases/tag/v5.0.12

**Comment by Sjors** [comment]
@jtormey I'm getting a ton of `TypeError: Cannot read property 'iso2Code' of undefined` in a production build. I reverted to 5.0.11 for the time being. Not sure if this is a bug in https://github.com/blockchain/My-Wallet-V3-Frontend or this change.

errors

**Pull request merged**
